SoftQuiz/Models/AnswerSuggestion.cs
using Newtonsoft.Json;

namespace SoftQuiz.Models
{
    public class AnswerSuggestion
    {
        [JsonProperty("answer")]
        public string Answer { get; set; }

        [JsonProperty("isCorrect")]
        public bool IsCorrect { get; set; }

        [JsonProperty("answeredThis")]
        public bool AnsweredThis { get; set; }
    }
}

SoftQuiz/Models/QuizAnswer.cs
namespace SoftQuiz.Models
{
    public class QuizAnswer
    {
        public string AnswerId { get; set; }

        public bool IsCorrect { get; set; }
    }
}

SoftQuiz/Models/QuizQuestion.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SoftQuiz.Models
{
    public class QuizQuestion
    {
        public QuizQuestion()
        {
            _suggestedAnswers = new List<AnswerSuggestion>();
        }

        private List<AnswerSuggestion> _suggestedAnswers;

        [JsonProperty("question")]
        public string Question { get; set; }

        public IEnumerable<AnswerSuggestion> answerSuggestions
        {
            get
            {
                return _suggestedAnswers;
            }
            set
            {
                _suggestedAnswers = value.ToList();
            }
        }

    }
}

SoftQuiz/Models/QuizResult.cs
using System.Collections.Generic;
using System.Linq;

namespace SoftQuiz.Models
{
    public class QuizResult
    {
        private List<QuizAnswer> _answers;
        public string Zip { get; set; }

        public IEnumerable<QuizAnswer> Answers
        {
            get
            {
                return _answers;
            }
            set
            {
                _answers = value.ToList();
            }
        }

        public QuizResult()
        {
            _answers = new List<QuizAnswer>();
        }
    }
}

SoftQuiz/Controllers/HomeController.cs
using SoftQuiz.Extensions;
using SoftQuiz.Services;
using System.Collections.Generic;
using System.Web.Mvc;

namespace SoftQuiz.Controllers
{
    [OutputCache(Duration = 0)]
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<string> availableQuiz = QuizDataService.ListAvailableQuiz(this.GetApplicationRootPath());

            return View(availableQuiz);
        }

        [Route("Home/Quiz/{selectedQuiz}")]
        public ActionResult Quiz(string selectedQuiz)
        {
            ViewBag.SelectedQuiz = selectedQuiz;

            return View();
        }
    }
}

SoftQuiz/Controllers/QuizController.cs
using Newtonsoft.Json;
using SoftQuiz.Extensions;
using SoftQuiz.Models;
using SoftQuiz.Services;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Http;

namespace SoftQuiz.Controllers
{
    public class QuizController : ApiController
    {
        // GET: api/Quiz/scrum
        [HttpGet]
        [Route("api/Quiz/{quizName}")]
        public HttpResponseMessage Get(string quizName)
        {
            string jsonFile = QuizDataService.GetQuizData(this.GetApplicationRootPath(), quizName);

            var response = Request.CreateResponse(HttpStatusCode.OK);
            response.Content = new StringContent(jsonFile, Encoding.UTF8, "application/json");
            return response;
        }

        // POST: api/Quiz
        [HttpPost]
        public HttpResponseMessage Post([FromBody] QuizResult data)
        {
            // Do somthing with the posted data - i.e. log the result to db or ....

            int correctAnswers = 0;

            foreach (QuizAnswer qa in data.Answers)
            {
                if (qa.IsCorrect) correctAnswers++;
            }

            string resultString = string.Format("Du hade {0} rätt svar på {1} frågor.", correctAnswers, data.Answers.Count());
            string jsonData = JsonConvert.SerializeObject(resultString);

            var response = Request.CreateResponse(HttpStatusCode.OK);
            response.Content = new StringContent(jsonData, Encoding.UTF8, "application/json");
            return response;
        }


        /// <summary>
        /// Used to capture the raw json data
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [Route("api/Quiz/PostRawBufferManual")]
        public async Task<string> PostRawBufferManual()
        {
            string result = await Request.Content.ReadAsStringAsync();
            return result;
        }
    }
}

SoftQuiz/Views/Home/Index.cshtml
@model List<string>

<style>
    a {
        width:125px;
        height:180px;
        display:inline-block;
        background-position-x:left;
    }
</style>

@{
    foreach (string link in Model)
    {
        <div>
            @Html.ActionLink(" ", "Quiz", new { selectedQuiz = link }, new { style = "background-image: url('images/scrum.png')" })
        </div>
    }
}

SoftQuiz/Views/Home/Quiz.cshtml
@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>

    @*<script src="~/app/dataService.js"></script>*@
    <script src="~/app/softQuizController.js"></script>
}


<div id="angCont" ng-app="SoftQuizApplication" ng-controller="SoftQuizController" ng-init="loadQuiz('@HttpRuntime.AppDomainAppVirtualPath')">
    <input type="hidden" id="selectedQuiz" value="@ViewBag.SelectedQuiz" />
    <div ng-include="getInclude()"></div>
</div>

SoftQuiz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="-1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SoftQuiz</title>
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="body-content">
        @RenderBody()
    </div>
</body>
</html>